#!/bin/sh
# DicomRemap: apply an anonymization script to DICOM files
# Copyright (c) 2008,2009 Washington University
# Author: Kevin A. Archie <karchie@npg.wustl.edu>

LIBDIR=/usr/local/lib

if [ $JAVA_HOME ] ; then
	JAVA=${JAVA:-${JAVA_HOME}/bin/java}
else
	JAVA=${JAVA:-java}
fi

export CLASSPATH="$LIBDIR/DicomBrowser-1.7.0b5-bin-with-dependencies.jar"

"${JAVA}" -Djava.awt.headless=true org.nrg.dcm.edit.CSVRemapper $*
