#!/bin/sh
# DicomSummarize: Generates a CSV file for modifying DICOM
# attributes at Patient, Study, or Series levels.
# Copyright (c) 2008,2009 Washington University
# Author: Kevin A. Archie <karchie@npg.wustl.edu>

LIBDIR=/usr/local/lib

if [ $JAVA_HOME ] ; then
	JAVA=${JAVA:-${JAVA_HOME}/bin/java}
else
	JAVA=${JAVA:-java}
fi

export CLASSPATH="$LIBDIR/DicomBrowser-1.7.0b5-bin-with-dependencies.jar"

"${JAVA}" org.nrg.dcm.edit.CSVSummaryBuilder $*
