#!/bin/bash

OWD=`dirname $0`

# Exit with error status
die() {
    echo >&2 "$@"
    exit -1
}

[[ -e ${OWD}/vars.sh  ]] || die "vars.sh file is required for redeploy script"

source ${OWD}/vars.sh
source ${OWD}/macros

echo
echo Stopping Tomcat...
sudo service tomcat7 stop

# Reset database?
DESTROY=N
echo
read -p "Are you sure you want to reset the database? ALL DATABASE DATA IN THIS VM WILL BE DESTROYED. [y/N] " DESTROY

if [[ $DESTROY =~ [Yy] ]]; then
    echo
    echo "Dropping '${PROJECT}' database."
    dropdb -U $VM_USER $PROJECT
    echo
    echo "Creating new '${PROJECT}' database."
    createdb -U $VM_USER $PROJECT
fi

echo
echo Restarting Tomcat...
startTomcat

monitorTomcatStartup

STATUS=$?
if [[ ${STATUS} == 0 ]]; then
    echo "==========================================================="
    echo "Database reset completed successfully."
    echo "==========================================================="
    exit 0;
else
    echo The application does not appear to have started properly. Status code: ${STATUS}
    echo The last lines in the log are:; tail -n 40 /var/log/tomcat7/catalina.out;
fi

exit ${STATUS}
