# save this config's directory as #{cwd}
cwd     = File.dirname(File.expand_path(__FILE__))
cfg_dir = File.basename(Dir.getwd)

# then load the 'multi' Vagrantfile
eval(IO.read('../../scripts/Vagrantfile'), binding)
